### PR TITLE
Add refresh-commands.js to create/update global application command

### PR DESCRIPTION
**Pull request by WindSekirun**
This PR makes show commands list of `evobot` in discord command section

a660b11b63a95e932719346ff67ea60f

Usage: node refresh-commands {applicationId}
ex) node refresh-commands 123456789123456789

**OBJECTIVE**
* collect name, description and send request to discord api server
* refactor initialization of i18n(#350) into locale.js

### CODE REVIEW

**Review by wolf-yuan-6115 — CHANGES_REQUESTED** [review]
Yeah you can play a music with slash command and you can't give it any args
So u can't play music with slash command...

**Comment by WindSekirun** [comment]
@wolf-yuan-6115 according to [docs](https://discord.com/developers/docs/interactions/slash-commands#example-walkthrough), we can give args into commands. but we need to provide `options` like below code.

```
"options": [
        {
            "name": "user",
            "description": "Get or edit permissions for a user",
            "type": 2 // 2 is type SUB_COMMAND_GROUP
        },
        {
            "name": "role",
            "description": "Get or edit permissions for a role",
            "type": 2
        }
    ]
```

So, below commands will need additional working to provide `args`.
* clip
* move
* play
* playlist
* remove
* search
* skipto

**Comment by WindSekirun** [comment]
@wolf-yuan-6115 I added `slashargs` into play and other comnands, like this (description will be korean, but it depends locale settings on config.json)

```
{
	"name": "clip",
	"description": "주어진 클립을 재생합니다.",
	"options": [
		{
			"name": "url",
			"description": "사용 방법: /play <YouTube URL | Video Name | Soundcloud URL>",
			"type": 3,
			"required": true
		}
	]
}
```

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 according to [docs](https://discord.com/developers/docs/interactions/slash-commands#example-walkthrough), we can give args into commands. but we need to provide `options` like below code.
> 
> ```
> "options": [
>         {
>             "name": "user",
>             "description": "Get or edit permissions for a user",
>             "type": 2 // 2 is type SUB_COMMAND_GROUP
>         },
>         {
>             "name": "role",
>             "description": "Get or edit permissions for a role",
>             "type": 2
>         }
>     ]
> ```
> 
> So, below commands will need additional work to provide `args`.
> * clip
> * move
> * play
> * playlist
> * remove
> * search
> * skipto

Play command args type is 3 (string), and permission command args type is not 2, user and role's type are 6 and 8.

**Comment by dylanjamesdev** [comment]
Is the point of this to just "show off your command" or? There's no way this would work, there's no interactions manager anywhere within this.

**Review by wolf-yuan-6115 — COMMENTED** [review]
This script won't let u to use slash command list to use bot, I don't think it's useful.

**Comment by eritislami** [comment]
Currently not usable due to changes in discord.js@13

**Pull request closed without merging**
