### PR TITLE
Updated/Added some things

### PR DESCRIPTION
**Pull request by rexjohannes**
+ botname config value
+ example soundcloud id
+ sharding system
+ better debuging
+ status config value
+ update config at readme.md
+ ubuntu install skript (beta) (ubuntu.sh) needs that this pull get merged to work

### CODE REVIEW

**Comment by rexjohannes** [comment]
(Tested all - working!)

**Comment by JoJoSniper** [comment]
Hi, how do I remove the shard? I recently just removed it and it seems to still be there even running without the shard.js

**Comment by rexjohannes** [comment]
To use no sharding start the bot without shard.js

**Comment by JoJoSniper** [comment]
I did but I keep getting this and it keeps repeating
[WS => Shard 0] Heartbeat acknowledged, latency of 40ms.

**Comment by SugarD-x** [comment]
Shard 0 should be your own server.

**Comment by JoJoSniper** [comment]
How do I stop the repeating console logging of 
[WS => Shard 0] Heartbeat acknowledged, latency of 40ms.
though

**Comment by rexjohannes** [comment]
Just remove client.on("debug", (e) => console.info(e)); in index.js

**Comment by Muhammad-Hadidi** [comment]
Make the help menu better.
*help: https://cdn.discordapp.com/attachments/759189195465687110/759189222090473541/help.png
*help help: https://cdn.discordapp.com/attachments/759189195465687110/759189224011595816/help-help.png

**Comment by ParasDeshpande** [comment]
Btw anyone wondering why is it always shard 0, you need to set the main in package.json to shard.js for sharding to work properly...

**Comment by chino-chan1** [comment]
so, we still use node index.js or shard.js?

**Comment by rexjohannes** [comment]
Use node shard.js if u want to start with sharding

**Comment by ParasDeshpande** [comment]
> so, we still use node index.js or node shard.js?

So shard.js is basically your manager that wraps the main index.js... so Shard.js has all control over how many instances of index.js (or the main client file) should run... So you have to mention the main file in shard.js which it should run and shard.js will start running your index.js (or the main client file) on its own...
Although the bot is fine without sharding until it reaches 1k+ servers... Wouldn't recommend having that... Coz it would just use up more resources on your server to manage each instance... also note that the bot does not divide the servers on shards equally... it uses a formula to calculate which server goes on which shard which is based on the total shard count and server id... mentioned in the docs on developer portal... So i don't think this is useful on small bots...

**Pull request closed without merging**
