### PR TITLE
Save playlist function

### PR DESCRIPTION
**Pull request by henry-bao**
# Hi all 👋 
## Recently, I have moved my bot's music system to Lavalink entirely, so I've decided to share some of my old codes that are based on ytdl. 

This includes the [**save playlist**] features I wrote for my bot. In order for these features to work, you will need to have a [MongoDB](https://www.mongodb.com/) server set up, and paste the connection URI into `config.json` or `.env`.

## Here are the commands: (`[]` = required, `<>` = optional),

💾 `/playlist-save [playlist name]`  - Self-explanatory, saves the current queue into a database so you could play later

▶️ `/playlist-play [playlist name]` - Plays a saved playlist. Simple enough

📃 `/playlist-list  <playlist name>` - Displays all of your playlists if no playlist name was entered. If one is entered, it will display the content inside the playlist

🖊️ `/playlist-edit [playlist name]`  - This command will allow you to add and delete songs in a playlist as well as renaming the playlist. An embedded message will guide you through the process

🗑️ `/playlist-delete [playlist name]` - Self-explanatory, deletes a playlist by name

### If you spot any issues, don't hesitate to leave a comment 😄
_All I am asking is some credit if you want to implement these features in your bot_ 👍🏼

### CODE REVIEW

**Comment by UnDeadLolomat** [comment]
Working very good! Is there a way to only show server specific playlists when i type playlist-list tho ? Like to only show the playlists for the server which the command was typed in.

**Review by wolf-yuan-6115 — APPROVED** [review]

**Comment by ChronHD** [comment]
Do these commands only require you to paste the mongodb URI in your config? or is other work needed

**Comment by henry-bao** [comment]
> Do these commands only require you to paste the mongodb URI in your config? or is other work needed
Yea I believe that is all you need to do, if any issue comes up just leave a comment and I will take a look at it

**Comment by arz03** [comment]
> > Do these commands only require you to paste the mongodb URI in your config? or is other work needed
> 
> Yea I believe that is all you need to do, if any issue comes up just leave a comment and I will take a look at it

what connection type do i have to choose in mongodb cluster connection

**Comment by eritislami** [comment]
Closing as this was left behind a long time now

**Pull request closed without merging**
