### PR TITLE
Support Spotify Playlist

### LINKED ISSUE #185: Spotify Playlist Playback
It would be cool for the bot to be able to convert a Spotify playlist to a YouTube playlist automatically for playback purposes. I love using the bot so far and keep up the good work!

### PR DESCRIPTION
**Pull request by booleans-oss**
Fix #185 

## Approach
Fetching the ten first tracks of the Spotify playlist with link (c.f. [limitations](#Limitations) about links). For each track, [ytld](https://www.npmjs.com/package/ytdl-core) does research in order to have the closest youtube equivalent of the track based on the title from Spotify. And fill the [playlist video's array](https://github.com/eritislami/evobot/blob/master/commands/playlist.js#L47) as usual. 

## Limitations
[@ytld-core](https://www.npmjs.com/package/ytdl-core) is slow so it takes few seconds for the dependency to load the 10 songs (I reduced the playlist length to 10 but it still takes quite a few seconds to load the playlist which I don't think there is any solution). 

## Testing
I didn't use a wide range of samples in order to test the feature so it might need more testing. I have tested with 5 playlists (Spotify and not Spotify) but we never know where an error can come from ...

### CODE REVIEW

**Comment by booleans-oss** [comment]
Don't mind my math error for the refresh token, thought for a second that interval accepts seconds rather than milliseconds 

I'll change it tomorrow first thing

**Comment by BlazeIsClone** [comment]
Im getting this error, YouTube links work but cant get the Spotify links to play.
`TypeError: Cannot read property 'url' of undefined                                                                                                                                       at Object.execute (/mnt/d/Code/evobot/commands/play.js:88:50)   `

**Comment by booleans-oss** [comment]
@BlazeIsClone Thank you very much for testing

Can you describe me a way to reproduce your error (link used, files changed)

**Comment by BlazeIsClone** [comment]
> @BlazeIsClone Thank you very much for testing
> 
> Can you describe me a way to reproduce your error (link used, files changed)

I tested in two ways

1. implemented your pull request to my own project (copied your code manually) 

   **2. Cloned dev branch from your evobot fork (booleans-oss/evobot)**

In both cases I had to make few adjustments to get the code working, 
This was the error:

`(node:8583) UnhandledPromiseRejectionWarning: WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API. `

**I was able to fix this by making some minor adjustments to some environment variable names.**

after fixing that I got this error: 

`TypeError: Cannot read property 'url' of undefined at Object.execute (/mnt/d/Code/evobot/commands/play.js:88:50)`

Btw I have noticed you deleted or modified the dev branch in your repo https://github.com/booleans-oss/evobot 

Thank you :D

**Comment by booleans-oss** [comment]
@BlazeIsClone Yep, my branch name was incorrect and there were so many typos error in my files so I closed this PL

> `(node:8583) UnhandledPromiseRejectionWarning: WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.`
That error was basically caused by my typo in the variable name, I'm sorry x) But it should be corrected

Try using the my new PL (#437 ), it seems to be less errors even though there needs to be a might fix. My test samples were based on Spotify mobile app which causes the links to be different, so I'll fix this to support both Desktop and Mobile Spotify Links

**Comment by BlazeIsClone** [comment]
> @BlazeIsClone Yep, my branch name was incorrect and there were so many typos error in my files so I closed this PL
> 
> > `(node:8583) UnhandledPromiseRejectionWarning: WebapiAuthenticationError: An authentication error occurred while communicating with Spotify's Web API.`
> > That error was basically caused by my typo in the variable name, I'm sorry x) But it should be corrected
> 
> Try using the my new PL (#437 ), it seems to be less errors even though there needs to be a might fix. My test samples were based on Spotify mobile app which causes the links to be different, so I'll fix this to support both Desktop and Mobile Spotify Links

@booleans-oss oh good work thank you for implementing this 👍 

Good luck and I will keep in touch and provide you feedback :D

**Pull request closed without merging**
