### PR TITLE
Allow streaming of live audio (mp3)

### PR DESCRIPTION
**Pull request by maartenpeels**
Added the possibility to stream from an mp3 URL (ex. online radio stream)

### CODE REVIEW

**Comment by SugarD-x** [comment]
You are a god. I literally just checked the pull requests, hoping someone created this feature.

**Comment by rexjohannes** [comment]
#722

**Comment by Sourack** [comment]
The duration should be a value of 0 to show in live in nowplaying command.

**Comment by rexjohannes** [comment]
Please change the Stream Regex and select any url that is not yt or soundcloud as stream to support radio stations that dont uses .mp3 as file ending

**Comment by maartenpeels** [comment]
Using other streams did not seem to work.

This ticket can be picked up by someone else, or be closed. I started creating my own music streaming bot.

**Comment by eritislami** [comment]
Thank you, I will try to implement this after the refactor #1136

**Pull request closed without merging**
