### PR TITLE
Pageable Queue

### PR DESCRIPTION
**Pull request by badRyuk**
A simple pageable queue which can be controlled with reactions instead of sending separate embeds. Edits the single embed which is sent as the queue. Great for large queues and does not flood the queue channel if the queue is too big by sending too many embed messages. Also as some people add large playlists to the music bot this can help a lot!

### CODE REVIEW

**Comment by kasepta** [comment]
how to delete embed after press "⏹" ?

**Comment by badRyuk** [comment]
> how to delete embed after press "⏹" ?
@kasepta Sorry for the late reply. If you want to delete the embed message on reacting/pressing "⏹" here is what to do. 
Hear at line number 33 edit and add this:

**Comment by kasepta** [comment]
> > how to delete embed after press "⏹" ?
> 
> @kasepta Sorry for the late reply. If you want to delete the embed message on reacting/pressing "⏹" here is what to do.
> Hear at line number 33 edit and add this:
> 
> ```
>  } else {
>                 collector.stop();
>                 reaction.message.reactions.removeAll();
>                 queueEmbed.delete();
>             }
> ```
> 
> So you basically add `queueEmbed.delete()` below `reaction.message.reactions.removeAll();`
> I believe that should work haven't tried it myself

i got this error
`Missing Permissions - [ADD_REACTIONS, MANAGE_MESSAGES]!`

**Comment by eritislami** [comment]
Thanks will check this soon

**Review by eritislami — APPROVED** [review]

**Comment by SpaceLeft** [comment]
add track spotify please

**Pull request merged**
