### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SatyamSSJ10**
added new instructions on how to deploy, since before dotenv on index.js wasn't set up

### CODE REVIEW

**Comment by rexjohannes** [comment]
Dude this Readme is very shitty

**Comment by wolf-yuan-6115** [comment]
Heroku doesn't need .env file

**Comment by SatyamSSJ10** [comment]
Indeed but other free hoating site does like replit.com or glitch

**Comment by wolf-yuan-6115** [comment]
Huh, can you improve your markdown?

**Comment by SatyamSSJ10** [comment]
> Huh, can you improve your markdown?

I'll try to, tbh it's actually my first time making a readme or something like this

**Pull request closed without merging**
