### PR TITLE
Dj role permission

### PR DESCRIPTION
**Pull request by ktsuttlemyre**
I added a comprehensive DJ role permission.
Set DJ_ROLE in config.json or in environment variable via DJ_ROLE
This will auto set 'loop,move,pause,pruning,remove,shuffle,skip,skipto,volume,stop' to only be called by a user with the DJ_ROLE pillage set within discord.
DJ_ROLE check is done on commands as well as reaction actions.
DJ_COMMAND list can be customized in config or environment variables.

Also updated the Activity status to sound nicer :-)

Thanks for your attention! Look for more contributions from me in the future

### CODE REVIEW

**Review by wolf-yuan-6115 — CHANGES_REQUESTED** [review]
If `DJ_COMMANDS` is array it will be better

**Comment by ktsuttlemyre** [comment]
Updated DJ_COMMANDS to be array.

**Comment by Deepjq** [comment]
This is not working

**Comment by ktsuttlemyre** [comment]
I've been using it. Works fine for me. What issue are you running into?

**Comment by L0SER8228** [comment]
Can you add voteskip? If a user don't have dj role then he can skip a song by voting. The users on the voice channel, will react and if 50%+ users vote , then the song will be skipped

**Comment by ktsuttlemyre** [comment]
@L0SER8228 I think that should be another feature. If this ever gets merged voteskip would be my next contribution. Thanks for the suggestion :-)

**Comment by GameWatch21** [comment]
i know it's weird to ask on a pull request 1 year ago, but i try to use this code and have `isDjOnly not defined`

Maybe i type something wrong? or the dj role name is wrong

**Comment by eritislami** [comment]
Closing as this was left behind a long time now, will consider for the future

**Pull request closed without merging**
