### PR TITLE
Youtube search, play and playlist support without API key

### PR DESCRIPTION
**Pull request by Shiro-Nek0**
Removed the necessity for an Youtube API key to search, play and add playlists by using the [Youtube-sr](https://www.npmjs.com/package/youtube-sr) API

### CODE REVIEW

**Comment by eritislami** [comment]
Thanks this looks good so far, I will try to make time and test it in the next 2 weeks.

**Comment by Shiro-Nek0** [comment]
> 
> 
> @Shiro-Nek0 Am getting a error with your fork , it shows 'fetch is not a function'

It's a bug with the YouTube-sr library version in Linux (tested on Debian 10) fixed by downgrading it to 4.1.7, on Windows 10 4.1.8 works correctly see https://github.com/DevSnowflake/youtube-sr/issues/35, I will update the package.json when a fixed version come out, but for now 4.1.7 seems to work flawlessly on both Linux and Windows.

**Comment by NikosProGamer** [comment]
i tried this on my bot, works completely fine. no issues. goodjob

**Comment by Goldenfreddy0703** [comment]
Hey guys sorry for bothering but does Youtube search, play and playlist support without API key work well and could it be merged with the main branch by anychance? I used it and it works super well but i don't see why this pull requests is not merged.

**Comment by SugarD-x** [comment]
> Hey guys sorry for bothering but does Youtube search, play and playlist support without API key work well and could it be merged with the main branch by anychance? I used it and it works super well but i don't see why this pull requests is not merged.

Any update regarding this question? I'm wondering the same.

**Comment by Goldenfreddy0703** [comment]
Oh yeah I've been curious about this too.

**Comment by SugarD-x** [comment]
This may need redoing for the planned Discord.js 13 changes the bot's author has planned. Would be pretty nice to have this be available for it, as YouTube is getting pretty ridiculous with their API requirements now, and it is killing off music bots everywhere. This is a great workaround. :)

**Comment by Goldenfreddy0703** [comment]
Ahhhh I knew somebody would say that. Let's hope this bot gets a rewrite, it sucks but needs a rewrite in the future 😅

**Comment by nikosszzz** [comment]
> This may need redoing for the planned Discord.js 13 changes the bot's author has planned. Would be pretty nice to have this be available for it, as YouTube is getting pretty ridiculous with their API requirements now, and it is killing off music bots everywhere. This is a great workaround. :)

Can confirm as working as of current Discord.js 13 changes.

**Comment by Goldenfreddy0703** [comment]
Wait, do we already have a working rewrite version already?

**Comment by nikosszzz** [comment]
> Wait, do we already have a working rewrite version already?

The latest commits with patches from here seem to be working perfectly for me. I also have the Spotify integration system from another pull request that someone made. Both working fine and well.

**Comment by Goldenfreddy0703** [comment]
Oh then that's good to hear. Let's hope nothing affects the bot after April 30th.

**Comment by eritislami** [comment]
I will try to reintroduce this pull request after my planned general refactoring is done #1136 
#992 #907

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much and your the best. 😁

**Comment by eritislami** [comment]
Finally adopted in #1140

**Pull request closed without merging**
