### PR TITLE
🚀 Conversion to Slash-Commands

### PR DESCRIPTION
**Pull request by LagKnowsWhy**
This pull request updates the prefix commands of the discord music bot to use up-to-date slash commands. The purging command has been removed due to missing authentication in the original code. And an initializing sequence has been added to provide a better user experience.

### CODE REVIEW

**Comment by LagKnowsWhy** [comment]
I also added the ability to see when a `/play` command didn't return any URL, when searching for the name of the video.

**Comment by eritislami** [comment]
Thank you, this is huge, will take me a bit to review everything

**Comment by LagKnowsWhy** [comment]
A minor flaw which I just noticed are the missing translations in all the other languages, except English

**Comment by huntergregal** [comment]
Excited for this - #1332 applies

**Review by LagKnowsWhy — COMMENTED** [review]
stoked 🔥

**Comment by eritislami** [comment]
I have gone over your changes and made a lot of modifications to your PR

- Merged old/new commands to only be slash commands, not supporting both systems for the future
- Merged old/new MusicQueue
- Types were not used properly & there was // @ts-ignore everywhere
- Updated interfaces to match new command signature
- I migrated the search command to use a select menu interaction
- Overall code formatting & cleaning

Thanks for kickstarting this migration

**Comment by LagKnowsWhy** [comment]
Yeah sorry for the not so clean code. I didn't have much time and just wanted to see this project progress :P

**Pull request merged**
