### PR TITLE
Create Procfile

### PR DESCRIPTION
**Pull request by Himura16**

### CODE REVIEW

**Comment by sarthaktexas** [comment]
Could you also add an `app.json` file and a reply to Heroku button on the README before @eritislami merges?

**Review by sarthaktexas — CHANGES_REQUESTED** [review]
said in comment above

**Comment by eritislami** [comment]
I understand why you would want to submit a Procfile but personally i don't see any reason to include it in the project, i think if anyone is using heroku they can add it themselves, plus heroku can detect if procfile is missing and will use the start script from package.json

```js
"scripts": {
    "start": "node index.js"
  }
```

**Comment by eritislami** [comment]
I don't have access to push commits so i added the changes directly

**Comment by sarthaktexas** [comment]
the reason why there should be a procfile is because heroku defaults to using a web node, not a worker node. this prevent bots from joining channels, receiving webhook messages, sending webhook messages, etc.

**Pull request closed without merging**
