### PR TITLE
bot stop queue when alone for 2 minutes

### PR DESCRIPTION
**Pull request by ccauvang**
bot stop quueue when alone for 2 minutes

### CODE REVIEW

**Comment by Moazlion** [comment]
How to make it so it stays in the vc 24/7?

**Comment by Takiyo0** [comment]
Don't forget to delete the player from queue `client.queue.delete(oldState.guild.id` after `queue.connection.dispatcher.end()`, otherwise the bot won't join back when you want to play music because it'll just add the song to the queue without trying to join vc back https://github.com/eritislami/evobot/blob/4681a9fca4ed0225da4ebff94aef31d6757efc4d/commands/play.js#L131

**Comment by ccauvang** [comment]
> Don't forget to delete the player from queue `client.queue.delete(oldState.guild.id` after `queue.connection.dispatcher.end()`, otherwise the bot won't join back when you want to play music because it'll just add the song to the queue without trying to join vc back
> 
> https://github.com/eritislami/evobot/blob/4681a9fca4ed0225da4ebff94aef31d6757efc4d/commands/play.js#L131

you sure?

**Comment by eritislami** [comment]
Will be handled by the discord upgrade in v13

**Pull request closed without merging**
