### PR TITLE
Update string-progressbar

### PR DESCRIPTION
**Pull request by Sourack**

### CODE REVIEW

**Comment by omiinaya** [comment]
does this also fix the api issues introduced a few days ago?

**Comment by Sourack** [comment]
> does this also fix the api issues introduced a few days ago?

I don't know. What are the issues ?

**Comment by yizheng5946** [comment]
image

**Comment by Sourack** [comment]
It's not an issue this api is working like this when the bar is not 100 characters of lenght. Unfortunatly, I can't fix that.

**Comment by wolf-yuan-6115** [comment]
> image
> 

Maybe try to fix that yourself

**Pull request closed without merging**
