### PR TITLE
Add optional channel filter

### PR DESCRIPTION
**Pull request by sciencegirl100**
Use a channel filter from the config to only allow specified channel IDs

### CODE REVIEW

**Comment by LucaBarbaLata** [comment]
the code you provided works? i want to add this to my bot

**Comment by sciencegirl100** [comment]
> the code you provided works? i want to add this to my bot

Yeah, insert stereotypical "it works on my server" 

I totally suggest giving it a shot

**Comment by LucaBarbaLata** [comment]
Thanks i will try it

⁣

**Comment by LucaBarbaLata** [comment]
Does it work for you? It dosent work for me 

⁣Get BlueMail for Android ​

**Pull request closed without merging**
