### PR TITLE
Added Embeds and Response Speed Improvements

### PR DESCRIPTION
**Pull request by JediThePro**
- Added embeds to have a good looking view and have beautiful style.

- Improved response duration by 5 ms.

### CODE REVIEW

**Comment by wolf-yuan-6115** [comment]
Keep your token and API key in a safe place, and I don't think your code will working well...

**Comment by JediThePro** [comment]
?

**Review by BlazeIsClone — CHANGES_REQUESTED** [review]
I got this error -
```
SyntaxError: Unexpected token 'const'
 const noQw = new MessageEmbed()
```
I fixed it by adding the missing brackets -
```
if (args[0] > queue.songs.length) {
      const noQw = new MessageEmbed()
    .setColor(0xda7272)
    .setTimestamp()
    .setTitle('Error!')
    .setDescription(`The queue is only ${queue.songs.length} songs long!`)

      return message.reply(noQw).catch(console.error);
}
```

**Comment by BlazeIsClone** [comment]
> I got this error -
> 
> ```
> SyntaxError: Unexpected token 'const'
>  const noQw = new MessageEmbed()
> ```
> 
> I fixed it by adding the missing brackets -
> 
> ```
> if (args[0] > queue.songs.length) {
>       const noQw = new MessageEmbed()
>     .setColor(0xda7272)
>     .setTimestamp()
>     .setTitle('Error!')
>     .setDescription(`The queue is only ${queue.songs.length} songs long!`)
> 
>       return message.reply(noQw).catch(console.error);
> }
> ```

This is for the skipto.js

**Comment by aimeine** [comment]
> ?

bro change ur token and api key, u leaked it in config.json.example

**Pull request closed without merging**
