### PR TITLE
add support for lyrics from genius

### PR DESCRIPTION
**Pull request by j0ashm**
On my instance of the bot, lyrics-finder always seemed to take a large amount of time to grab lyrics for a song, and at times even managed to get the wrong ones.
So, I worked up this little modification so that lyrics can be scraped from Genius instead.

### CODE REVIEW

**Review by wolf-yuan-6115 — CHANGES_REQUESTED** [review]
You don't need to use Genius lyrics API, go to npm and search a package named "findthelyrics" it can don't the lyrics on Genius and Musixmatch. Use "lyrics-finder" with "findthelyrics" is more better.

**Comment by mihawkman** [comment]
how do i do that? can you send me your lyrics.js code? thank you

**Comment by wolf-yuan-6115** [comment]
> how do i do that? can you send me your lyrics.js code? thank you

No, sorry, I won't share my bot's code, it's not open source.

**Comment by SrIzan10** [comment]
TypeError: Cannot set property 'locale' of undefined

**Comment by eritislami** [comment]
Not planning to maintain this currently

**Pull request closed without merging**
