### PR TITLE
Update ytdl-core to 4.0.4 and fix ytdl-core-discord error

### PR DESCRIPTION
**Pull request by wolf-yuan-6115**
I updated `ytdl-core` to 4.0.4 and rewrite some play code.
I hope this working good.

Now, `ytdl-core-discord` is not compatible with `ytdl-core` 4.0.4, but it's compatible with 4.0.3, if you are still using 4.0.3, you will get `Unable to retrieve video metadata`, so I rewrite some code.Now evobot can play YouTube song!

### CODE REVIEW

**Comment by mihawkman** [comment]
when i try to do it, The codes gives me bunch of red lines

**Comment by eritislami** [comment]
I don't think you understand, I don't want to switch away from ytdl-core-discord, it helps avoid using ffmpeg and plays music more efficiently. We just have to wait for the package to be updated.

**Comment by wolf-yuan-6115** [comment]
> I don't think you understand, I don't want to switch away from ytdl-core-discord, it helps avoid using ffmpeg and plays music more efficiently. We just have to wait for the package to be updated.

Ok

**Comment by BlazeIsClone** [comment]
@wolf-yuan-6115 thank you for looking into this!, I managed to get the code working with some minor tweaking to your code and got the v4.0.4 working. I was gonna post my code but the old meta errors still persist. I think we just have to wait until a fix come out to the library.

**Comment by wolf-yuan-6115** [comment]
> I don't think you understand, I don't want to switch away from ytdl-core-discord, it helps avoid using ffmpeg and plays music more efficiently. We just have to wait for the package to be updated.

@eritislami Sorry for ping after this PR is closed. I checked discord.js source code and looks like it will automatically convert unknown stream to opus stream by using same package as ytdl-core-discord. In some emergency case, this can be solution.

**Pull request closed without merging**
