### PR TITLE
Create index1.js

### PR DESCRIPTION
**Pull request by SatyamSSJ10**
for heruko/repl.it webpage / also added 'process.env', but you need to ping bot to use

### CODE REVIEW

**Comment by wolf-yuan-6115** [comment]
no need, it will use more ram and cpu usage, and bot might will be down because DDoS attack

**Comment by SatyamSSJ10** [comment]
> no need, it will use more ram and cpu usage, and bot might will be down because DDoS attack

I added it so that people can keep it online with uptimerobot, like me XD

**Comment by wolf-yuan-6115** [comment]
i know... But you want to waste ram and cpu to run web process...
And **bot will be slow or stop if you got DDoS attack**

**Comment by wolf-yuan-6115** [comment]
And... You don't need to use dotenv
process.env is already existed in pure Node js

**Comment by SatyamSSJ10** [comment]
> And... You don't need to use dotenv
> process.env is already existed in pure Node js

Then why didn't it work on heruko and repl.it?

**Comment by wolf-yuan-6115** [comment]
> > And... You don't need to use dotenv
> > process.env is already existed in pure Node js
> 
> Then why didn't it work on heruko and repl.it?

it's working fine for me

**Pull request closed without merging**
