### PR TITLE
Support Spotify playlist

### LINKED ISSUE #185: Spotify Playlist Playback
It would be cool for the bot to be able to convert a Spotify playlist to a YouTube playlist automatically for playback purposes. I love using the bot so far and keep up the good work!

### PR DESCRIPTION
**Pull request by booleans-oss**
Fix #185 
(new pull due to wrong branch name, only figured out while waking up, my bad)

## Approach
Fetching the ten first tracks of the Spotify playlist with link (c.f. [limitations](#Limitations) about links). For each track, [ytld](https://www.npmjs.com/package/ytdl-core) does research in order to have the closest youtube equivalent of the track based on the title from Spotify. And fill the [playlist video's array](https://github.com/eritislami/evobot/blob/master/commands/playlist.js#L47) as usual. 

## Limitations
[@ytld-core](https://www.npmjs.com/package/ytdl-core) is slow so it takes few seconds for the dependency to load the 10 songs (I reduced the playlist length to 10 but it still takes quite a few seconds to load the playlist which I don't think there is any solution). 

## Testing
I didn't use a wide range of samples in order to test the feature so it might need more testing. I have tested with 5 playlists (Spotify and not Spotify) but we never know where an error can come from ...

### CODE REVIEW

**Comment by totolerigolo324** [comment]
if I understand with your method it could also work with Deezer?

**Comment by BlazeIsClone** [comment]
Hello! so I tested your latest commit and I saw your fixes and they work although the links still wont play Spotify music,
I know your aware of this ill be in touch.

The error:
`TypeError: Cannot read property 'url' of undefined at Object.execute (/mnt/d/Code/evobot/commands/play.js:88:50) `

Let me know if anyone had this same issue.
Thanks, Have a good day!

**Comment by booleans-oss** [comment]
> if I understand with your method it could also work with Deezer?
Indirectly, yes. The approach I have explained is not as straight forward as it may seem. In fact, what I have basically done is that I have used a dependency in order to log into Spotify API (with `SPOTIFY_CLIENT_ID` and `SPOTIFY_CLIENT_SECRET`) in order to have an access token (which is required to use Spotify API). If you want the code with Deezer, you would have to find the equivalent, meaning doing a search on Deezer API, authenticating your app - or using a dependency as I said before.

So you won't be able originally but the code might be similar. Just the authentication part would look different.



> Hello! so I tested your latest commit and I saw your fixes and they work although the links still wont play Spotify music,
> I know your aware of this ill be in touch.
> 
> The error:
> `TypeError: Cannot read property 'url' of undefined at Object.execute (/mnt/d/Code/evobot/commands/play.js:88:50) `
> 
> Let me know if anyone had this same issue.
> Thanks, Have a good day!

Thank you for testing. The error is located in ``play.js`` which means that the playlist code is doing good. Are you using the *playlist command* or the *play command* ? Because a Spotify playlist URL won't work with the play command.

In any case, do you mind sending me the URL you are using? I would be able to reproduce the error in order to solve it.

**Comment by BlazeIsClone** [comment]
@booleans-oss 

So I ran some tests and found out some interesting results!

The **play command** doesn't work entirely (I tested with both individual songs and playlists just to make sure)

The error:
```
TypeError: Cannot read property 'url' of undefined
    at Object.execute (/mnt/d/Code/evobot/commands/play.js:104:50)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The **Playlist command** does work and these were my findings:

If I were to search a playlist from Spotify (playlists not saved in my account) and play, It would not work although If I were to play a song from **My saved playlists** (the once I've added to my account) it would work 100%. This also works for **Radio** playlists as well.

This sums up if the playlists were saved in my account It would work without a problem if not I would get an error message:

```
WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Not found..
    at _toError (/mnt/d/Code/evobot/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /mnt/d/Code/evobot/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/mnt/d/Code/evobot/node_modules/superagent/lib/node/index.js:905:3)
    at /mnt/d/Code/evobot/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/mnt/d/Code/evobot/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:315:20)
    at Unzip.<anonymous> (/mnt/d/Code/evobot/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  body: { error: { status: 404, message: 'Not found.' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Sat, 05 Dec 2020 12:40:49 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 404
}
```

Btw I also tested with a VPN as well just to be safe and the results were the same.

_Lol I reached my youtube api quota(10K requests) after testing about 15 playlists. < I used a token exclusively to this testing_
_just wondering if that's realistic._

Thank You,
Have a good day,
I hope my findings were helpful!

**Comment by totolerigolo324** [comment]
I think I will try to do to deezer. So no problem for people who use personal deezer playlists.

**Comment by cris30054** [comment]
How can I put music from Spotify?

**Comment by totolerigolo324** [comment]
> How can I put music from Spotify?

it's simple we get the titles of the songs from the playlist via the sporitfy API and we look for them on youtube via ytdl-core to then play them with ytdl-core-discord

**Comment by cris30054** [comment]
> > How can I put music from Spotify?
> 
> it's simple we get the titles of the songs from the playlist via the sporitfy API and we look for them on youtube via ytdl-core to then play them with ytdl-core-discord

and there is no other way for the playlists because I put one and it gave me a video about the singer

**Comment by ItsLeon15** [comment]
**_WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: No token provided.
    at _toError (/home/container/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /home/container/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/home/container/node_modules/superagent/lib/node/index.js:905:3)
    at /home/container/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/home/container/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:314:20)
    at Unzip.<anonymous> (/home/container/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  body: { error: { status: 401, message: 'No token provided' } },
  headers: {
    'www-authenticate': 'Bearer realm="spotify"',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-type': 'application/json',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Tue, 02 Feb 2021 12:14:34 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 401
}_**

**Comment by ItsLeon15** [comment]
I've entered a correct and refreshed API Token however it doesn't work? Also,

**Comment by ItsLeon15** [comment]
**_(node:26) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at Object.execute (/home/container/commands/playlist.js:74:75)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)_**

**_else if(spotifyValid) {
      const msg = await message.channel.send(":gear: [0/10] Converting Spotify Playlist into Youtube Playlist");
        const linkPattern = /.*?\?/gi;
        let spotifyLink = url.split("/");
        spotifyLink = spotifyLink[spotifyLink.length-1].match(linkPattern)[0].slice(0, -1);
        try {
          let BasePlaylist = await message.client.spotify.getPlaylistInfo(spotifyLink);
          playlist = {
            title: BasePlaylist.title,
            url: args[0]
          };_**

**Pull request closed without merging**
