### PR TITLE
feat: play soundcloud playlists

### PR DESCRIPTION
**Pull request by zackradisic**
Recently updated soundcloud-downloader to facilitate playing playlists better, so I thought this would be a nice addition to the bot. 

The only caveat is that if the playlist has a lot of tracks it will take a little bit longer to load the playlist. I tested it with a playlist with 40 tracks and it took ~10 seconds to load.

### CODE REVIEW

**Comment by Sakura-49** [comment]
You need to add regex in the play command about soundcloud playlist

**Comment by zackradisic** [comment]
Thanks, just added it

**Comment by zackradisic** [comment]
@eritislami what do you think?

**Comment by eritislami** [comment]
> @eritislami what do you think?

Thanks this is great, haven't been very active on github lately due to work and being very busy IRL

**Comment by xSphere18** [comment]
please add code i can host for uptimerobot or other website.
thanks you...

**Pull request merged**
