### PR TITLE
Add STAY_TIME config to handle channel leave

### PR DESCRIPTION
**Pull request by WindSekirun**
* Related discussion: https://github.com/eritislami/evobot/discussions/333

Objectives
* Add STAY_TIME configs to handle channel leave when queue ended
* 0 will instant leave, other (300000ms) will leave after 300000ms (5 mins)

### CODE REVIEW

**Comment by eritislami** [comment]
I had to make a modification because if you tried to play a new song while timeout was active it would add to the old queue and then leave the channel without playing more music

**Comment by PrashLucifer** [comment]
How do I make the bot never leave vc even after the song ends, I wanna keep the bot 24/7 in vc, is that possible @eritislami

**Comment by WindSekirun** [comment]
@PrashLucifer I think you can give some big value into STAY_TIME (ex, 31556952 will 1 year)

**Comment by PrashLucifer** [comment]
> @PrashLucifer I think you can give some big value into STAY_TIME (ex, 31556952 will 1 year)

It is not working I created a variable in Heroku named STAY_TIME and put there very high value like 99999999999999 but the bot left the vc instantly

**Comment by WindSekirun** [comment]
@PrashLucifer Oh, i didn't know setTimeout has some limit. (according to https://catonmat.net/settimeout-setinterval)

So, bot can't stay over 25 days in these time. But you can remove setTimeout function on [these part](https://github.com/eritislami/evobot/pull/351/files#diff-53ff7dfc9a97fd18d36205c6de0a06cde46138b6ad492c5c67b156d3c0bf3636R12)

**Comment by PrashLucifer** [comment]
> @PrashLucifer Oh, i didn't know setTimeout has some limit. (according to https://catonmat.net/settimeout-setinterval)
> 
> So, bot can't stay over 25 days in these time. But you can remove setTimeout function on [these part](https://github.com/eritislami/evobot/pull/351/files#diff-53ff7dfc9a97fd18d36205c6de0a06cde46138b6ad492c5c67b156d3c0bf3636R12)

Can you help me out?

**Comment by PrashLucifer** [comment]
@WindSekirun If I give access to the forked repository, can you make changes and help me out?

**Comment by WindSekirun** [comment]
@PrashLucifer It looks like this would be easy, you can do it yourself. (I don't have time to help out)

* Open 'include/play.js' in your favorite editor (If doesn't exist, i recommand vscode)
* Delete 12~16 lines of that file
  ```
   setTimeout(function () {
        if (queue.connection.dispatcher && message.guild.me.voice.channel) return;
        queue.channel.leave();
        queue.textChannel.send("Leaving voice channel...");
      }, STAY_TIME * 1000);
  ```
* npm run start

**Comment by PrashLucifer** [comment]
> @PrashLucifer It looks like this would be easy, you can do it yourself. (I don't have time to help out)
> 
> * Open 'include/play.js' in your favorite editor (If doesn't exist, i recommand vscode)
> * Delete 12~16 lines of that file
>   ```
>    setTimeout(function () {
>         if (queue.connection.dispatcher && message.guild.me.voice.channel) return;
>         queue.channel.leave();
>         queue.textChannel.send("Leaving voice channel...");
>       }, STAY_TIME * 1000);
>   ```
> * npm run start

I deleted the portion u said, and then the bot stayed in the vc after the song ended but the Heroku app crashed and eventually bot left the vc

**Comment by PrashLucifer** [comment]
@WindSekirun

**Comment by PrashLucifer** [comment]
@WindSekirun 2020-12-02T10:33:11.250079+00:00 app[web.1]: 
2020-12-02T10:33:12.199999+00:00 app[web.1]: Pixel ready!
2020-12-02T10:34:08.548667+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-12-02T10:34:08.569012+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-12-02T10:34:08.683268+00:00 heroku[web.1]: Process exited with status 137
2020-12-02T10:34:08.719157+00:00 heroku[web.1]: State changed from starting to crashed
2020-12-02T10:39:22.431295+00:00 app[api]: Set STAY_TIME config vars by user prashamshah17@gmail.com
2020-12-02T10:39:22.431295+00:00 app[api]: Release v25 created by user prashamshah17@gmail.com
2020-12-02T10:39:22.666728+00:00 heroku[web.1]: State changed from crashed to starting
2020-12-02T10:39:29.194624+00:00 heroku[web.1]: Starting process with command `npm start`
2020-12-02T10:39:33.185743+00:00 app[web.1]: 
2020-12-02T10:39:33.185768+00:00 app[web.1]: > evobot@0.9.0 start
2020-12-02T10:39:33.185768+00:00 app[web.1]: > node index.js
2020-12-02T10:39:33.185769+00:00 app[web.1]: 
2020-12-02T10:39:35.697973+00:00 app[web.1]: Pixel ready!
2020-12-02T10:39:47.958371+00:00 app[web.1]: [33mWARNING:[0m ytdl-core is out of date! Update with "npm install ytdl-core@latest".
2020-12-02T10:39:52.199741+00:00 app[web.1]: [33mWARNING:[0m ytdl-core is out of date! Update with "npm install ytdl-core@latest".
2020-12-02T10:40:04.273869+00:00 app[web.1]: DiscordAPIError: Missing Permissions
2020-12-02T10:40:04.273878+00:00 app[web.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2020-12-02T10:40:04.273879+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2020-12-02T10:40:04.273879+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:93:5)
2020-12-02T10:40:04.273880+00:00 app[web.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
2020-12-02T10:40:04.273881+00:00 app[web.1]:   method: 'delete',
2020-12-02T10:40:04.273881+00:00 app[web.1]:   path: '/channels/752595573038776325/messages/783643601351606282/reactions',
2020-12-02T10:40:04.273882+00:00 app[web.1]:   code: 50013,
2020-12-02T10:40:04.273883+00:00 app[web.1]:   httpStatus: 403
2020-12-02T10:40:04.273883+00:00 app[web.1]: }
2020-12-02T10:40:29.543240+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-12-02T10:40:29.570358+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-12-02T10:40:29.676185+00:00 heroku[web.1]: Process exited with status 137
2020-12-02T10:40:29.763496+00:00 heroku[web.1]: State changed from starting to crashed

the error on Heroku, can you help fixing this?

**Comment by WindSekirun** [comment]
@PrashLucifer Let's continue these discussion on [here](https://github.com/eritislami/evobot/discussions/412)

**Pull request merged**
